// Stonk Actions
export const SET_STONK_LIST = "GET_STONK_LIST";
export const CHANGE_SELECTED_STONK_LIST = "CHANGE_SELECTED_STONK_LIST";

// Chart Actions
export const SET_CHART_LIST = "GET_CHART_LIST";
export const CHANGE_SELECTED_CHART_LIST = "CHANGE_SELECTED_CHART_LIST";

// General Actions
export const CLEAR_SELECTED_STONKS_CHARTS = "CLEAR_SELECTED_STONKS_CHARTS";
